### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by luzik** [Tinkerforge/brickv#18]
Please consider moving to v5 of Qt libs because it is quite hard to get PyQT4 this days. My personal issue is to get it running on Mac OSX HighSierra under python2. There is no any problem with python3 and PyQT5

**Comment by borg42** [comment]
Yes this is already planned. For the longest time we couldn't do it because PyQt5 bindings for Python3 were not available in Debian stable and we wanted brickv to run on it.

Porting to Python3 is unfortunately a bit of a hassle, because we have lots of Python2 strings that have to be carefully changed to Python3 bytes, especially in the RED Brick code. We expect this to be a few weeks of work and testing.

**Comment by luzik** [comment]
Yeah ..I did moving to python3 with some BrickletRS232 code and this take time..
Thank You for clarification !

**Comment by borg42** [comment]
Unfortunately we don't have a fixed date yet, but it is definitely on the TODO list.

**Comment by rtrbt** [comment]
Version 2.4.0 is using Python3 and PyQt5.
